/**
 * TurboQuant Compression Demo — Two-Kernel Pipeline
 *
 * Demonstrates end-to-end quantization-based compression on VLIW SIMD hardware:
 *
 *   DDR (input I8 matrices)
 *     │  DMA write to DMEM
 *     ▼
 *   Kernel 1 — Matrix Engine (projection)
 *     coarse_keys × coarse_queries^T + residual_keys × residual_queries^T
 *     → 32×32 U32 score matrix in DMEM
 *     │
 *     ▼
 *   Kernel 2 — Vector Engine (sign extraction) + Scalar Engine (bit packing)
 *     For each row of 32 scores:
 *       sign_bits[i] = (score[i] >= 0) ? 1 : 0     [vector shr + xor]
 *       packed_code  = OR(sign_bits[i] << i)         [scalar shl + or]
 *     → 32 packed U32 binary codes in DMEM
 *     │  DMA read from DMEM
 *     ▼
 *   DDR (compressed output)
 *
 * Compression:
 *   Input:  32×32 I8 matrix  = 8,192 bits  (1,024 bytes)
 *   Output: 32 packed U32    = 1,024 bits  (  128 bytes)
 *   Ratio:  8× compression
 *
 * Artifacts are generated by:
 *   python tools/turboquant_demo.py --compress --emit-dir <artifact_dir>
 *
 * Usage:
 *   ./example_turboquant_compress <artifact_dir>
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "vliw_driver.h"

/* Platform addresses (Zynq PS / FPGA) */
#define VLIW_CSR_BASE   0x60000000
#define VLIW_DDR_BASE   0x40000000

/* DDR layout */
#define PROG_DDR_OFFSET      0x00000000
#define DATA_DDR_OFFSET      0x00100000
#define AXI_BEAT_BYTES       64

/* DDR data sub-offsets (byte addresses within DATA_DDR_OFFSET) */
#define COARSE_KEYS_DDR      (DATA_DDR_OFFSET + 0u)         /* 1024 bytes */
#define COARSE_QUERIES_DDR   (DATA_DDR_OFFSET + 1024u)      /* 1024 bytes */
#define RESIDUAL_KEYS_DDR    (DATA_DDR_OFFSET + 2048u)      /* 1024 bytes */
#define RESIDUAL_QUERIES_DDR (DATA_DDR_OFFSET + 3072u)      /* 1024 bytes */
#define SCORES_DDR           (DATA_DDR_OFFSET + 4096u)      /* 4096 bytes (32×32 U32) */
#define COMPRESSED_DDR       (DATA_DDR_OFFSET + 8192u)      /* 128 bytes  (32 U32)    */

/* ------------------------------------------------------------------ */
/*  File I/O helpers (same pattern as example_matrix_matmul_32x32.c)  */
/* ------------------------------------------------------------------ */

static uint32_t *read_hex_words(const char *path, size_t *count_out) {
    FILE *fp = fopen(path, "r");
    char line[64];
    size_t cap = 2048, count = 0;
    uint32_t *words;
    if (fp == NULL) return NULL;
    words = (uint32_t *)malloc(cap * sizeof(uint32_t));
    if (words == NULL) { fclose(fp); return NULL; }
    while (fgets(line, sizeof(line), fp) != NULL) {
        unsigned int value = 0;
        if (sscanf(line, "%x", &value) != 1) continue;
        if (count == cap) {
            cap *= 2;
            uint32_t *grown = (uint32_t *)realloc(words, cap * sizeof(uint32_t));
            if (grown == NULL) { free(words); fclose(fp); return NULL; }
            words = grown;
        }
        words[count++] = (uint32_t)value;
    }
    fclose(fp);
    *count_out = count;
    return words;
}

static uint8_t *read_binary_file(const char *path, size_t *size_out) {
    FILE *fp = fopen(path, "rb");
    long size;
    uint8_t *data;
    if (fp == NULL) return NULL;
    if (fseek(fp, 0, SEEK_END) != 0) { fclose(fp); return NULL; }
    size = ftell(fp);
    if (size < 0) { fclose(fp); return NULL; }
    rewind(fp);
    data = (uint8_t *)malloc((size_t)size);
    if (data == NULL) { fclose(fp); return NULL; }
    if (fread(data, 1, (size_t)size, fp) != (size_t)size) { free(data); fclose(fp); return NULL; }
    fclose(fp);
    *size_out = (size_t)size;
    return data;
}

static int load_program(vliw_handle_t *h, const uint32_t *words, size_t word_count) {
    uint32_t words_per_bundle = h->bundle_width / 32;
    size_t bundle_count;
    uint8_t beat[AXI_BEAT_BYTES];
    size_t b, copy_bytes;
    if (words_per_bundle == 0) words_per_bundle = 1;
    bundle_count = word_count / words_per_bundle;
    for (b = 0; b < bundle_count; b++) {
        memset(beat, 0, sizeof(beat));
        copy_bytes = words_per_bundle * 4;
        if (copy_bytes > AXI_BEAT_BYTES) copy_bytes = AXI_BEAT_BYTES;
        memcpy(beat, &words[b * words_per_bundle], copy_bytes);
        vliw_ddr_write(h, PROG_DDR_OFFSET + b * AXI_BEAT_BYTES, beat, AXI_BEAT_BYTES);
    }
    return vliw_load_program(h, VLIW_DDR_BASE + PROG_DDR_OFFSET,
                              (uint32_t)bundle_count, 1000000);
}

/* ------------------------------------------------------------------ */

int main(int argc, char **argv) {
    const char *dir;
    char path[512];
    vliw_handle_t vliw;

    size_t k1_word_count = 0, k2_word_count = 0;
    uint32_t *k1_imem = NULL, *k2_imem = NULL;
    size_t ck_sz = 0, cq_sz = 0, rk_sz = 0, rq_sz = 0, exp_sz = 0;
    uint8_t *coarse_keys = NULL, *coarse_queries = NULL;
    uint8_t *residual_keys = NULL, *residual_queries = NULL;
    uint8_t *expected_compressed = NULL;
    uint8_t actual_compressed[128]; /* 32 × 4 bytes */
    int rc;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <artifact_dir>\n", argv[0]);
        return 1;
    }
    dir = argv[1];

    /* --- Load artifacts --- */

    snprintf(path, sizeof(path), "%s/turboquant_compress_k1_imem_words.txt", dir);
    k1_imem = read_hex_words(path, &k1_word_count);

    snprintf(path, sizeof(path), "%s/turboquant_compress_k2_imem_words.txt", dir);
    k2_imem = read_hex_words(path, &k2_word_count);

    snprintf(path, sizeof(path), "%s/turboquant_compress_coarse_keys_i8.bin", dir);
    coarse_keys = read_binary_file(path, &ck_sz);

    snprintf(path, sizeof(path), "%s/turboquant_compress_coarse_queries_i8.bin", dir);
    coarse_queries = read_binary_file(path, &cq_sz);

    snprintf(path, sizeof(path), "%s/turboquant_compress_residual_keys_i8.bin", dir);
    residual_keys = read_binary_file(path, &rk_sz);

    snprintf(path, sizeof(path), "%s/turboquant_compress_residual_queries_i8.bin", dir);
    residual_queries = read_binary_file(path, &rq_sz);

    snprintf(path, sizeof(path), "%s/turboquant_compress_expected_compressed_u32_le.bin", dir);
    expected_compressed = read_binary_file(path, &exp_sz);

    if (!k1_imem || !k2_imem || !coarse_keys || !coarse_queries
        || !residual_keys || !residual_queries || !expected_compressed) {
        fprintf(stderr, "Failed to load artifacts from %s\n", dir);
        goto cleanup_fail;
    }
    if (ck_sz != 1024 || cq_sz != 1024 || rk_sz != 1024 || rq_sz != 1024 || exp_sz != 128) {
        fprintf(stderr, "Unexpected sizes: ck=%zu cq=%zu rk=%zu rq=%zu exp=%zu\n",
                ck_sz, cq_sz, rk_sz, rq_sz, exp_sz);
        goto cleanup_fail;
    }

    printf("=== TurboQuant Compression Demo ===\n\n");
    printf("Input:  32x32 I8 matrix  = 8192 bits (1024 bytes per matrix)\n");
    printf("Output: 32 packed U32    = 1024 bits (128 bytes)\n");
    printf("Compression ratio: 8x\n\n");

    /* --- Initialize hardware --- */

    vliw_init(&vliw, (uint32_t *)VLIW_CSR_BASE, (uint8_t *)VLIW_DDR_BASE);
    vliw_reset(&vliw);

    /* --- Step 1: Write input data from DDR (host) to DMEM region --- */

    printf("Step 1: Loading input matrices from DDR to DMEM...\n");
    vliw_ddr_write(&vliw, COARSE_KEYS_DDR,      coarse_keys,    ck_sz);
    vliw_ddr_write(&vliw, COARSE_QUERIES_DDR,    coarse_queries, cq_sz);
    vliw_ddr_write(&vliw, RESIDUAL_KEYS_DDR,     residual_keys,  rk_sz);
    vliw_ddr_write(&vliw, RESIDUAL_QUERIES_DDR,  residual_queries, rq_sz);
    printf("  4 x 1024-byte I8 tile matrices written to DDR.\n");

    /* --- Step 2: Run Kernel 1 — Matrix projection --- */

    printf("\nStep 2: Running Kernel 1 (matrix projection, %zu IMEM words)...\n",
           k1_word_count);
    if (load_program(&vliw, k1_imem, k1_word_count) != 0) {
        fprintf(stderr, "Timed out loading Kernel 1 into IMEM\n");
        goto cleanup_fail;
    }
    vliw_start(&vliw);
    rc = vliw_wait_halted(&vliw, 10000000);
    if (rc != 0) {
        fprintf(stderr, "Timed out waiting for Kernel 1 to halt\n");
        goto cleanup_fail;
    }
    printf("  Kernel 1 complete (%u cycles). Score matrix in DMEM[1024..2047].\n",
           vliw_get_core_cycles(&vliw, 0));

    /* --- Step 3: Run Kernel 2 — Binarize + pack --- */
    /* Scores remain in DMEM at word 1024; Kernel 2 reads them and writes
       compressed output to DMEM word 2048. */

    printf("\nStep 3: Running Kernel 2 (binarize + pack, %zu IMEM words)...\n",
           k2_word_count);
    vliw_reset(&vliw);
    if (load_program(&vliw, k2_imem, k2_word_count) != 0) {
        fprintf(stderr, "Timed out loading Kernel 2 into IMEM\n");
        goto cleanup_fail;
    }
    vliw_start(&vliw);
    rc = vliw_wait_halted(&vliw, 10000000);
    if (rc != 0) {
        fprintf(stderr, "Timed out waiting for Kernel 2 to halt\n");
        goto cleanup_fail;
    }
    printf("  Kernel 2 complete (%u cycles). Compressed codes in DMEM[2048..2079].\n",
           vliw_get_core_cycles(&vliw, 0));

    /* --- Step 4: Read compressed output from DMEM to DDR --- */

    printf("\nStep 4: Reading compressed binary codes from DMEM...\n");
    vliw_ddr_read(&vliw, COMPRESSED_DDR, actual_compressed, 128);

    /* --- Verify --- */

    if (memcmp(actual_compressed, expected_compressed, 128) != 0) {
        fprintf(stderr, "\nERROR: Compressed output mismatch!\n");
        fprintf(stderr, "Expected first 4 words:");
        for (int i = 0; i < 4; i++) {
            uint32_t exp_word;
            memcpy(&exp_word, expected_compressed + i * 4, 4);
            fprintf(stderr, " 0x%08X", exp_word);
        }
        fprintf(stderr, "\nActual   first 4 words:");
        for (int i = 0; i < 4; i++) {
            uint32_t act_word;
            memcpy(&act_word, actual_compressed + i * 4, 4);
            fprintf(stderr, " 0x%08X", act_word);
        }
        fprintf(stderr, "\n");
        goto cleanup_fail;
    }

    printf("\n=== Compression Verified ===\n");
    printf("  32x32 I8 input  -> 32 packed U32 output\n");
    printf("  %d bits in  ->  %d bits out  =  8x compression\n", 8192, 1024);
    printf("  Engines used: Matrix (projection) + Vector (sign) + Scalar (pack)\n");
    printf("\nFirst 4 compressed binary codes:\n");
    for (int i = 0; i < 4; i++) {
        uint32_t word;
        memcpy(&word, actual_compressed + i * 4, 4);
        printf("  Row %2d: 0x%08X\n", i, word);
    }

    free(k1_imem); free(k2_imem);
    free(coarse_keys); free(coarse_queries);
    free(residual_keys); free(residual_queries);
    free(expected_compressed);
    return 0;

cleanup_fail:
    free(k1_imem); free(k2_imem);
    free(coarse_keys); free(coarse_queries);
    free(residual_keys); free(residual_queries);
    free(expected_compressed);
    return 1;
}
